---
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run ci
      
  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.7.0
        with:
          github-token: ${{secrets.github_token}}
